name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./my-app 
        run: npm ci

        # Step 4: Run unit tests with coverage
      - name: Run tests and collect coverage
        run: npm run test:coverage

      # Step 5: Upload coverage results as an artifact
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage

      # Optional: Display test results in the Actions tab
      - name: Publish coverage summary
        run: cat ./coverage/lcov-report/index.html

