name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./my-app

      - name: Run tests and collect coverage
        run: npm run test:coverage
        working-directory: ./my-app

      - name: Debug coverage directory
        run: ls -l ./my-app/coverage
        
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./my-app/coverage # Correct path here

      - name: Publish coverage summary
        run: cat ./my-app/coverage/index.html
